name: Release build
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build ${{ matrix.target }}"
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    env:
      CARGO_INCREMENTAL: 1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ matrix.target }}
      - name: Restore source codes' timestamps
        uses: chetan/git-restore-mtime-action@v1
      - name: Set SDK for macOS aarch64
        if: matrix.target == 'aarch64-apple-darwin'
        run: |
          sudo xcode-select -s "/Applications/Xcode_12.4.app"
          sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
      - name: Setup rustup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}
